fix(ci): upgrade SSL db

diff --git a/.github/workflows/Setup.Nginx.Proxy.yaml b/.github/workflows/Setup.Nginx.Proxy.yaml
--- a/.github/workflows/Setup.Nginx.Proxy.yaml
+++ b/.github/workflows/Setup.Nginx.Proxy.yaml
@@ -83,11 +83,26 @@ jobs:
           echo "✅ Certbot ready."
 
           # -----------------------------------------------------
-          # 1. HTTP config for Certbot validation
+          # 1. Issue SSL certificate
+          # -----------------------------------------------------
+          echo "🔍 Checking SSL certificate for $DOMAIN..."
+          if [ -d "$CERT_PATH" ] && [ -f "$CERT_PATH/fullchain.pem" ]; then
+            echo "✅ SSL certificate already exists at $CERT_PATH"
+          else
+            echo "📜 Requesting new SSL certificate..."
+            if ! echo "$SERVER_PASSWORD" | sudo -S certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos -m roberthost.vn@gmail.com; then
+              echo "❌ Failed to issue SSL certificate. Check DNS and port 80 access."
+              exit 1
+            fi
+            echo "✅ SSL certificate successfully issued for \$DOMAIN"
+          fi
+
+          # -----------------------------------------------------
+          # 2. HTTPS config for Certbot validation
           # -----------------------------------------------------
           echo "🧱 Creating temporary HTTP-only config for \$DOMAIN ..."
           cat <<CONFIG > temp.conf
-          # Stream TCP proxy for PostgreSQL & MongoDB no SSL
+          # Stream TCP proxy for PostgreSQL & MongoDB with SSL
 
           # --- PostgreSQL Proxy ---
           upstream postgres_backend {
@@ -95,14 +110,22 @@ jobs:
           }
 
           server {
-              listen 15432;
+              listen 15432 ssl;
 
               # Proxy TCP
               proxy_pass postgres_backend;
 
+              # SSL
+              ssl_certificate     /etc/letsencrypt/live/database.ssrengineering.te>
+              ssl_certificate_key /etc/letsencrypt/live/database.ssrengineering.te>
+
               # Timeout
               proxy_timeout 10m;
               proxy_connect_timeout 10s;
+
+              # SSL options safety
+              ssl_protocols TLSv1.2 TLSv1.3;
+              ssl_ciphers HIGH:!aNULL:!MD5;
           }
 
           # --- MongoDB Proxy ---
@@ -111,14 +134,22 @@ jobs:
           }
 
           server {
-              listen 27018;
+              listen 27018 ssl;
 
               # Proxy TCP
               proxy_pass mongo_backend;
 
+              # SSL
+              ssl_certificate     /etc/letsencrypt/live/database.ssrengineering.tech>
+              ssl_certificate_key /etc/letsencrypt/live/database.ssrengineering.tech>
+
               # Timeout
               proxy_timeout 10m;
               proxy_connect_timeout 10s;
+
+              # SSL options safety
+              ssl_protocols TLSv1.2 TLSv1.3;
+              ssl_ciphers HIGH:!aNULL:!MD5;
           }
           CONFIG
 
